import Group from '../models/Group.js';
import User from '../models/User.js';
import Expense from '../models/Expense.js';
import Settlement from '../models/Settlement.js';
import calculateBalances from '../utils/calculateBalances.js';
import { notifyGroupMembers } from '../utils/createNotifications.js';

const access = (group, userId) => group && group.members.some((member) => String(member._id || member) === String(userId));
async function getGroup(id, userId) { const group = await Group.findById(id).populate('members', 'fullName email username').populate('createdBy', 'fullName email username'); return access(group, userId) ? group : null; }
export async function listGroups(req, res) { res.json(await Group.find({ members: req.user._id }).populate('members', 'fullName username email').populate('createdBy', 'fullName username email').sort('-createdAt')); }
export async function listUsers(req, res) { res.json(await User.find({ _id: { $ne: req.user._id } }).select('fullName username email').sort('fullName')); }
export async function createGroup(req, res) { const selectedMembers = Array.isArray(req.body.memberIds) ? req.body.memberIds : []; const members = [req.user._id, ...selectedMembers.filter((id) => String(id) !== String(req.user._id))]; const group = await Group.create({ name: req.body.name, members: [...new Set(members.map(String))], createdBy: req.user._id }); if (req.body.identifier) { const query = req.body.identifier.includes('@') ? { email: req.body.identifier.toLowerCase() } : { username: req.body.identifier.toUpperCase() }; const invited = await User.findOne(query); if (invited && !group.members.some((id) => String(id) === String(invited._id))) { group.members.push(invited._id); await group.save(); } } await notifyGroupMembers(group, { actorId: req.user._id, type: 'group-created', message: `${req.user.fullName} added you to ${group.name}.` }); res.status(201).json(await group.populate('members', 'fullName username email')); }
export async function getOne(req, res) { const group = await getGroup(req.params.id, req.user._id); if (!group) return res.status(404).json({ message: 'Group not found' }); res.json(group); }
export async function invite(req, res) { const group = await getGroup(req.params.id, req.user._id); if (!group) return res.status(404).json({ message: 'Group not found' }); const query = req.body.identifier?.includes('@') ? { email: req.body.identifier.toLowerCase() } : { username: req.body.identifier.toUpperCase() }; const member = await User.findOne(query); if (!member) return res.status(404).json({ message: 'User not found' }); const alreadyMember = group.members.some((id) => String(id) === String(member._id)); if (!alreadyMember) { group.members.push(member._id); await group.save(); await notifyGroupMembers({ ...group.toObject(), members: [member._id] }, { actorId: req.user._id, type: 'group-invite', message: `${req.user.fullName} added you back to ${group.name}.` }); } res.json(await group.populate('members', 'fullName username email')); }
export async function leave(req, res) { const group = await getGroup(req.params.id, req.user._id); if (!group) return res.status(404).json({ message: 'Group not found' }); const [expenses, settlements] = await Promise.all([Expense.find({ groupId: group._id }), Settlement.find({ groupId: group._id })]); const balances = calculateBalances(expenses, settlements); const outstanding = Object.entries(balances).filter(([key]) => key.split('_').includes(String(req.user._id))).reduce((total, [, amount]) => total + amount, 0); if (outstanding > 0.009) return res.status(400).json({ message: `You cannot leave this group because you have an outstanding balance of $${outstanding.toFixed(2)}.` }); await notifyGroupMembers(group, { actorId: req.user._id, type: 'group-left', message: `${req.user.fullName} left ${group.name}.` }); group.members = group.members.filter((member) => String(member._id || member) !== String(req.user._id)); await group.save(); res.json({ message: 'You left the group' }); }
export async function balances(req, res) { const group = await getGroup(req.params.id, req.user._id); if (!group) return res.status(404).json({ message: 'Group not found' }); const [expenses, settlements] = await Promise.all([Expense.find({ groupId: group._id }).populate('paidBy', 'fullName username').populate('splits.userId', 'fullName username'), Settlement.find({ groupId: group._id }).populate('from to', 'fullName username')]); const raw = calculateBalances(expenses, settlements); const rows = Object.entries(raw).map(([key, amount]) => { const [from, to] = key.split('_'); return { from: group.members.find((m) => String(m._id) === from), to: group.members.find((m) => String(m._id) === to), amount }; }); res.json({ balances: rows }); }
